# config.yaml

version: trainval  # or 'trainval' etc.
dataroot: ./data/nuscenes

model:
  downsample: 16
  camC: 64
  outC: 6

data_aug:
  H: 900
  W: 1600
  resize_lim: [0.193, 0.225]
  final_dim: [128, 352]
  bot_pct_lim: [0.0, 0.22]
  rot_lim: [-5.4, 5.4]
  rand_flip: true
  ncams: 5
  cams: [CAM_FRONT_LEFT, CAM_FRONT, CAM_FRONT_RIGHT, 
          CAM_BACK_LEFT, CAM_BACK, CAM_BACK_RIGHT]

grid_conf:
  xbound: [-50.0, 50.0, 0.5]
  ybound: [-50.0, 50.0, 0.5]
  zbound: [-10.0, 10.0, 20.0]
  dbound: [4.0, 45.0, 1.0]

optim:
  lr: 0.001
  weight_decay: 1e-7
  max_grad_norm: 5.0

loader:
  batch_size: 64
  nworkers: 2

trainer:
  epochs: 50
  gpus: 1
  log_freq: 500
  precision: 32


loss:
  pos_weight: 1 # tbc

logdir: ./runs
