# config.yaml

model:
  downsample: 16
  camC: 64
  outC: 6

dataset:
  name: nuscenes
  version: trainval  # 'mini' or 'trainval'
  dataroot: ./data/nuscenes
  semantic_layer: ['drivable_area',
                    'ped_crossing',
                    'walkway',
                    'stop_line',
                    'carpark_area',
                    'lane_divider']

data_aug:
  H: 900
  W: 1600
  resize_lim: [0.320, 0.373]
  final_dim: [288, 512]
  bot_pct_lim: [0.0, 0.22]
  rot_lim: [-5.4, 5.4]
  rand_flip: true
  ncams: 5
  cams: [CAM_FRONT_LEFT, CAM_FRONT, CAM_FRONT_RIGHT, 
          CAM_BACK_LEFT, CAM_BACK, CAM_BACK_RIGHT]

grid_conf:
  xbound: [-50.0, 50.0, 0.5]
  ybound: [-50.0, 50.0, 0.5]
  zbound: [-10.0, 10.0, 20.0]
  dbound: [4.0, 45.0, 1.0]

optim:
  lr: 0.001
  weight_decay: 1e-7
  max_grad_norm: 5.0

loader:
  batch_size: 64
  nworkers: 2

trainer:
  epochs: 50
  gpus: 1
  log_freq: 20
  precision: 32

trainer_config:
  seed: 42  # Random seed for reproducibility
  lr: !!float 1e-3
  min_lr: !!float 1e-4
  iou_loss: lovasz  # Options: 'dice', 'lovasz'
  weight_decay: !!float 1e-4  #1e-4 for dice loss, 1e-2 for lovasz loss
  gpu_num: 1
  precision: 16-mixed
  epochs: 40
  warmup_percent: 0.1
  logger_freq: 100
  val_after_epoch: 0
  acc_grad_batches: 1 # Gradient accumulation steps (final_bs = bs * acc_grad_batches)
  resume_path: logs/01_11_19_40/best-ckpt-epoch=36-step=31783.ckpt
  pretrain_path: null


loss:
  pos_weight: 1 # tbc

logdir: ./runs
